[package]
name = "rust-opse"
version = "0.1.0"
authors = ["Alexis Tourneux <tourneuxalexis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
log = "*"
rust-crypto = "^0.2"
